name: better_player_web
version: 1.0.0

publish_to: none

flutter:
  plugin:
    platforms:
      web:
        pluginClass: BetterPlayerWeb
        fileName: better_player_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  video_js:
    git:
      url: https://github.com/uniqcast/video_js
      ref: 32c0aef8a0b71eb9e01bc668383e24534ce89b09
#  video_js:
#    path: '../../video_js'

  better_player_platform_interface:
    git:
      url: https://github.com/uniqcast/betterplayer
      ref: afc24df1c8452aa71c01828c99da8dd355167872
      path: better_player_platform_interface
#  better_player_platform_interface:
#    path: '../better_player_platform_interface'

dev_dependencies:
  flutter_lints: ^2.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"