name: better_player_web
version: 1.0.0

publish_to: none

flutter:
  plugin:
    platforms:
      web:
        pluginClass: BetterPlayerWeb
        fileName: better_player_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  video_js:
    git:
      url: https://github.com/uniqcast/video_js
      ref: 60d77f86506ac5ad4dab540c87812d9d77016363
  #  video_js:
  #    path: '../../video_js'

  #  better_player_platform_interface:
  #    git:
  #      url: git://github.com/flutter/packages.git
  #      ref: TODO
  #      path: better_player_platform_interface
  better_player_platform_interface:
    path: '../better_player_platform_interface'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"